#!/bin/bash

apt update
apt install -y git cmake build-essential subversion python3-dev libncurses5-dev libxml2-dev libedit-dev swig doxygen graphviz xz-utils ninja-build software-properties-common lsb-release gcc g++ sed sudo
#apt clean all
#wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
#apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
#apt install -y kitware-archive-keyring
#apt install -y cmake
sudo su
export C=/usr/bin/gcc
export CXX=/usr/bin/g++
cd /tmp
git clone --branch llvmorg-12.0.1 https://github.com/llvm/llvm-project.git

# Edit for Clangd to work with Jupyter .ipynb
sed -i "265i\\\t   .Case(\"ipynb\", TY_CXX)" /tmp/llvm-project/clang/lib/Driver/Types.cpp

mkdir -p /out/llvm
mkdir -p /out/build
cd /out/build
cmake /tmp/llvm-project/llvm -G Ninja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" -DLLVM_ENABLE_ASSERTS=On -DCMAKE_INSTALL_PREFIX=/out/llvm
ninja check-clangd
rm -rf /tmp/llvm-project

cd /out
tar -zcf ./jupyter-clangd.$(uname -m).tar.gz *

mkdir -p /data/out
mv /out/jupyter-clangd.$(uname -m).tar.gz /data/out
rm -rf /out
