name: hydrun-amd64

on:
  push:
  pull_request:
    
jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Setup hydrun
        run: |
          curl -L -o /tmp/hydrun "https://github.com/pojntfx/hydrun/releases/latest/download/hydrun.linux-$(uname -m)"
          install /tmp/hydrun /usr/local/bin
      - name: Chmod Hydrunfile
        run: chmod a+x ./Hydrunfile
      - name: Build with hydrun
        run: hydrun -a amd64 -o ubuntu ./Hydrunfile
      - name: Publish to GitHub releases
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "amd64"
          prerelease: false
          files: |
            out/*
